baseURL = "http://rm-rf.run/"
languageCode = "en-us"
title = "Hey"
theme = "one"

pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true
pygmentsStyle = "pygments"

[params]
    navigation = ["archives.md", "about.md"]

