baseURL = "http://localhost:1313/"
languageCode = "en-us"
title = "NotePad"
theme = "one"

pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true
pygmentsStyle = "pygments"

[params]
    navigation = ["archives.md", "about.md"]

